namespace YgoSoul.RapTech.Lib.YgoEdo.Abstractions.Card.Enum
{
    public enum CardType
    {
        Monster,
        Spell,
        Trap,
        Normal,
        Effect,
        Fusion,
        Ritual,
        TrapMonster,
        Spirit,
        Union,
        Gemini,
        Tuner,
        Synchro,
        Token,
        Maximum,
        QuickPlay,
        Continuous,
        Equip,
        Field,
        Counter,
        Flip,
        Toon,
        Xyz,
        Pendulum,
        SpSummon,
        Link
    }
}