namespace YgoSoul.RapTech.Lib.YgoEdo.Abstractions.Card.Enum
{
    public enum MonsterType
    {
        None,
        Warrior,
        SpellCaster,
        Fairy,
        Fiend,
        Zombie,
        Machine,
        Aqua,
        Pyro,
        Rock,
        WingedBeast,
        Plant,
        Insect,
        Thunder,
        Dragon,
        Beast,
        BeastWarrior,
        Dinosaur,
        Fish,
        SeaSerpent,
        Reptile,
        Psychic,
        Divine,
        CreatorGod,
        Wyrm,
        Cyberse,
        Illusion
    }
}