namespace YgoSoul.RapTech.Lib.Ygoedo.Manager.Interface.Enum;

public enum CardSearchCategory
{
    None,
    DestroyMonster,
    DestroySpellOrTrap,
    DestroyDeck,
    DestroyHand,
    SendToGrave,
    SendToHand,
    SendToDeck,
    Banish,
    Draw,
    Search,
    ChangeAtkDef,
    ChangeLevelRank,
    ChangePosition,
    Piercing,
    DirectAttack,
    MultiAttack,
    NegateActivation,
    NegateEffect,
    DamageLifePoints,
    RecoverLifePoints,
    SpecialSummon,
    NonEffectRelated,
    TokenRelated,
    FusionRelated,
    RitualRelated,
    SynchroRelated,
    XyzRelated,
    LinkRelated,
    CounterRelated,
    Gamble,
    Control,
    MoveZones
}